# Generated by Django 4.0 on 2022-01-03 14:36

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=50, null=True)),
                ('picture', cloudinary.models.CloudinaryField(blank=True, default='static/usericon.png', max_length=255, verbose_name='image')),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NeighborHood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('police_contact', models.IntegerField(blank=True, null=True)),
                ('hospital_contact', models.IntegerField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrator', to='hood.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='hood.neighborhood'),
        ),
    ]
