# Generated by Django 3.2.9 on 2022-01-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_auto_20220103_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='neighborhood',
        ),
    ]
