# Generated by Django 3.2.9 on 2022-01-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_remove_userprofile_neighborhood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
