# Generated by Django 3.2.9 on 2022-01-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0009_business_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='hospital_address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='hospital_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='police_address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='police_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
