# Generated by Django 3.2.9 on 2022-01-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0011_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='neighborhood',
        ),
    ]
